snuppy_manager/group/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.show_groups, name='show_group'),
    url(r'^add$', views.group_add, name='group_add'),
    url(r'^edit$', views.group_edit, name='group_edit'),
    url(r'^delete$', views.group_delete, name='group_delete'),

    url(r'^invite/user$', views.group_add_user, name='group_add_user'),
    url(r'^invite/accept$', views.accept_invite, name='accept_invite'),
    url(r'^invite/decline$', views.decline_invite, name='decline_invite'),
]

snuppy_manager/snuppy_manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', RedirectView.as_view(url='application/')),

    url(r'^account/', include('account.urls')),
    url(r'^application/', include('application.urls')),
    url(r'^group/', include('group.urls')),
    url(r'^version/', include('version.urls')),
]

snuppy_manager/application/models.py
from django.db.models import (CharField, DateTimeField, TextField,
    ForeignKey, Model, CASCADE, URLField)
from group.models import Group


#The application you develop
class Application(Model):
    name = CharField(max_length=100)
    group = ForeignKey(Group, on_delete=CASCADE)
    description = TextField()
    source_code = URLField()
    created_at = DateTimeField(auto_now_add=True)
    updated_at = DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

snuppy_manager/group/models.py
from django.db.models import (CharField, ForeignKey, Model,
                              CASCADE, ManyToManyField)

from account.models import Profile


#The group of users
class Group(Model):

    name = CharField(max_length=32)

    profile = ManyToManyField(Profile, through='Rule')

    def __str__(self):
        return self.name

    @staticmethod
    def get_user_groups(user_id):
        profile = Profile.objects.get(id=user_id)
        groups = Group.objects.filter(profile__id=profile.id)
        return groups

    @staticmethod
    def is_user_in_group(profile, group_id):
        for group in profile.group_set.values():
            if group['id'] == group_id:
                return True
        return False

    @staticmethod
    def is_user_admin_in_group(profile, group_id):
        for rule in profile.rule_set.values():
            if rule['group_id'] == group_id and rule['rule'] == 'A':
                return True
        return False


class Rule(Model):

    RULE_CHOICES = (
        ('A', 'Admin'),
        ('M', 'Manager'),
        ('G', 'Guest'),
        ('U', 'UserDefine'),
    )

    CHECK_VALUE = ('A', 'M', 'G', 'stay', 'remove', )

    group = ForeignKey(Group) #on_delete??
    profile = ForeignKey(Profile) #on_delete??
    rule = CharField(max_length=1, choices=RULE_CHOICES)

    @staticmethod
    def is_rule_exist(input_rule):
        if input_rule in Rule.CHECK_VALUE:
            return True
        return False

    @property
    def username(self):
        return self.profile.user.username

    @property
    def other_choices(self):
        return [ rule_type for rule_type in self.RULE_CHOICES if rule_type[1] != self.get_rule_display and rule_type[0] != 'U' ]


class Invite(Model):

    profile = ForeignKey(Profile, on_delete=CASCADE)
    group = ForeignKey(Group, on_delete=CASCADE)

    @staticmethod
    def is_user_have_invite(profile, group_id):
        for invite in profile.invite_set.values():
            if invite['group_id'] == group_id:
                return True
        return False

snuppy_manager/group/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.views.decorators.csrf import csrf_protect
from django.core.exceptions import ObjectDoesNotExist
from django.template.loader import render_to_string

from account.models import Profile
from .models import Group, Rule, Invite


#GROUPS

@login_required
@require_GET
def show_groups(request):
    user_id = request.user.id
    profile = Profile.objects.get(user=user_id)

    groups = Group.objects.filter(profile=profile, rule__rule='A')

    return render(request, 'group/show_all.html', {'groups':groups})


@csrf_protect
@login_required
@require_POST
def group_add(request):
    try:
        group_name = request.POST.get('group_name')
    except KeyError:
        return HttpResponseBadRequest # нету параментра group_name, форму подделали

    if Group.objects.filter(name=group_name).count() > 0: # группа с таким именем существуюет
        return JsonResponse({
            'error': 'Ошибка!',
            'error_text': 'Группа с именем {} уже существует!'.format(group_name)
        })

    user_id = request.user.id
    profile = Profile.objects.get(id=user_id)

    new_group = Group(name=group_name)
    new_group.save()
    rule = Rule(group=new_group, profile=profile, rule='A')
    rule.save()

    html = render_to_string('group/add_new.html', {'group': new_group})
    return HttpResponse(html)


@login_required
@require_http_methods(["GET", "POST"])
def group_edit(request):
    if request.method == 'GET':
        group_id = request.GET.get('group_id')
        group = Group.objects.get(id=group_id)
        rules = group.rule_set.all()

        return render(request, 'group/edit.html', {'rules':rules, 'group':group})
    elif request.method == 'POST':
        try:
            group_id = int(request.POST['group_id'])
        except (KeyError, ValueError):
            return HttpResponseBadRequest() # Если нет group_id значит форму подделали
        if not Group.is_user_admin_in_group(request.user.profile, group_id):
            return HttpResponseBadRequest() # Если отправитель не админ значит форму подделали

        for key in request.POST:
            try:
                _profile_id = int(key)
                profile = Profile.objects.get(id=_profile_id)
            except (ObjectDoesNotExist, ValueError):
                continue #в POST будут не только user_id - все не нужные пропускаем
            if not Group.is_user_in_group(profile, group_id):
                return HttpResponseBadRequest() #Если хотя бы один не в группе или не верное Rule значит форму подделали
            if not Rule.is_rule_exist(request.POST[key]): # Если указанного rule не существует, значит форму подделали
                return HttpResponseBadRequest()
            #.... all check done here
            if request.POST[key] == 'remove':
                profile.rule_set.get(group_id=group_id).delete()
            elif request.POST[key] == 'stay':
                continue
            else:
                rule = profile.rule_set.get(group_id=group_id)
                rule.rule = request.POST[key]
                rule.save()
        return HttpResponse('ok')


# adds the user as a response to invite
@login_required
@csrf_protect
@require_POST
def group_add_user(request):
    admin_profile = request.user.profile
    try:
        new_user = request.POST.get('_new_user')
        group_id = int(request.POST.get('_group_id_val'))
    except (KeyError, ValueError):
        return HttpResponseBadRequest() # если нет аргументов или group_id не число, значит форму подделали

    #verification procedures
    profile = Profile.check_profile(new_user)
    if not profile: # Проверяем, что введенный пользователь существует
        return JsonResponse({
            'error': 'Ошибка!',
            'error_text': 'Пользователя {} не существует'.format(new_user)
        })
    if not Group.is_user_admin_in_group(admin_profile, group_id): # Отправитель является админом группы
        return HttpResponseBadRequest  # Если не админ, значит форму подделали
    if Group.is_user_in_group(profile, group_id): # пользователь уже в группе
        return JsonResponse({
            'error': 'Ошибка!',
            'error_text': 'Пользователь {} уже в группе!'.format(new_user)
        })
    if Invite.is_user_have_invite(profile, group_id): # уже есть приглашение в группу
        return JsonResponse({
            'error': 'Ошибка!',
            'error_text': 'Пользователю {} уже отправленно приглашение!'.format(new_user)
        })

    #invitation itself
    group = Group.objects.get(id=group_id)
    invite = Invite(group=group, profile=profile)
    invite.save()
    return HttpResponse('success')


@login_required
@require_POST
def group_delete(request):
    try:
        group_id = int(request.POST.get('group_id'))
    except (KeyError, ValueError):
        return HttpResponseBadRequest # если не число или нет параметра, значит форму подделали
    try:
        group = Group.objects.get(id=group_id)
    except ObjectDoesNotExist:
        return HttpResponseBadRequest # группы не существует, форму подделали

    if not Group.is_user_admin_in_group(request.user.profile, group_id):
        return HttpResponseBadRequest # если не админ, значит форму подделали

    group.delete()
    # ВАЖНО!!!
    # group.delete() удалит вообще все: группу, все приложения в этой группе,
    # все версии удаленных приложений (кроме файлов!)
    return HttpResponse('Success')


@login_required
def decline_invite(request):
    if request.method == 'POST':
        group_id = request.POST.get('_group_id')
        group = Group.objects.get(id=group_id)
        profile = Profile.objects.get(user=request.user.id)

        invite = Invite.objects.get(group=group, profile=profile)
        invite.delete()
        #не делаем ни чего, просто удаляем приглашение.
        # Возможно нужно добавить информирование приглащающего,
        # что его приглашение отклонили?

        return redirect('/application/')
    else:
        return HttpResponseBadRequest()

# collaborates with accept_invite.js
@login_required
def accept_invite(request):
    if request.method == 'POST':
        group_id_str = ''
        invitations_str = request.POST.get('invitations_str')
        group_id_arr = [int(letter) for letter in invitations_str.rstrip(',').split(',')]

        for group_id in group_id_arr:
            # group_id = request.POST.get('_group_id')
            group = Group.objects.get(id=group_id)
            profile = Profile.objects.get(user=request.user.id)

            invite = Invite.objects.get(group=group, profile=profile)
            invite.delete()

            rule = Rule(group=group, profile=profile, rule='G')
            # новые пользователи добавляются с правами Guest
            rule.save()

        return redirect('/application/')
    else:
        return HttpResponseBadRequest()

snuppy_manager/group/templates/group/edit.html
{% extends "account_base.html" %}
{% block title %}Edit group{% endblock %}
{% block content %}
{% load staticfiles%}

<div class="container">
    <div class="row titles-margin">
        <div class="col-lg-7">
            <p class="titles">Группа {{ group.name }}</p>
        </div>
        <div class="col-lg-2 col-lg-offset-3">
            <form role="form" action="{% url 'show_group' %}" id="deleteGroup">
                <input type="submit" value="Удалить группу" class="btn btn-primary btn-shadow "/>
            </form>
            <form role="form" action="{% url 'show_group' %}">
                <input type="submit" value="Назад к группам" class="btn btn-primary btn-shadow"/>
            </form>

        </div>
    </div>

    <form role="form" action="{% url 'group_edit' %}" method="post" id="changeGroup">
        {% csrf_token %}
    <table class="table table-background">
        <tr>
            <th class="text-center">Логин пользователя</th>
            <th class="text-center">Уровень доступа</th>
            <th class="text-center">Изменить</th>
        </tr>
        {% for rule in rules %}
            {% if request.user.profile.id != rule.profile_id %}
                <tr>
                    <td class="text-center"> {{ rule.username }} </td>
                    <td class="text-center"> {{ rule.get_rule_display }} </td>
                    <td>
                        <select name="{{rule.profile.id}}" id="rule_new" class="form-control">
                            <option value="stay"> None </option>
                            {% for rule_type in rule.other_choices %}
                            <option value="{{ rule_type.0 }}"> {{ rule_type.1 }}</option>
                            {% endfor %}
                            <option value="remove"> Remove </option>
                        </select>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
    <input type="hidden" name="group_id" value="{{ group.id }}" id="group_id">
    <div class="col-lg-2 col-lg-offset-3">
        <input type="submit" value="Применить изменения" class="btn btn-primary btn-shadow "/>
    </div>
    </form>

    <div class="col-lg-2 col-lg-offset-3">
        <form role="form" action="invite/user" id="inviteUser">
            <label for="new_user">Имя пользователя</label>
            <input required type="text" class="form-control" id="new_user" name="new_user">
            <input type="submit" value="Пригласить пользователя" class="btn btn-primary btn-shadow "/>
        </form>

    </div>

</div>
<script src="{% static 'js/group_edit.js' %}"></script>
{% endblock %}

snuppy_manager/group/templates/group/show_all.html
{% extends "account_base.html" %}
{% block title %}Groups{% endblock %}
{% block content %}
{% load staticfiles%}

<div class="container">
    <div class="row titles-margin">
        <div class="col-lg-7">
            <p class="titles">Группы в которых вы являетесь администратором: </p>
        </div>
        <div class="col-lg-2 col-lg-offset-3">
            <form role="form" action="#" id="createGroupBtn">
                <input type="submit" value="Создать группу" class="btn btn-primary btn-shadow "/>
            </form>

        </div>
    </div>

    <table class="table table-background" id="groupTable">
        <tr>
            <th class="text-center">Имя группы</th>
            <th class="text-center">Участников</th>
            <th class="text-center">Приложений</th>
        </tr>
        {% for group in groups %}
        <tr>
            <td class="text-center"> <a href = 'edit?group_id={{group.id}}' class="groupLink">{{ group.name}} </a> </td>
            <td class="text-center">{{ group.profile.count }}</td>
            <td class="text-center"> {{ group.application_set.count }}</td>

        </tr>
        {% endfor %}
    </table>

</div>

<div id="createGroupMdl" class="modal fade" role="dialog">
    <div class="container add-list-margin">
        <div class="col-lg-6 col-lg-offset-3">
            <div class="add-list">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <p class="titles titles-margin">Создание новой группы</p>
                <form role="form" action="#" id="createGroupSend">
                     {% csrf_token %}
                    <div class="form-group">
                        <label for="group_name">Имя группы:</label>
                        <input required type="text" class="form-control" id="group_name" name="group_name" >
                    </div>
                    <div class="add-app-btn-container">
                        <input type="submit" value="Создать" class="btn btn-primary add-app-btn" />
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Отмена</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>


<script src="{% static 'js/group_create.js' %}"></script>

{% endblock %}